services:
  asylum-seekers-assistant:
    build: .

    container_name: asylum-seekers-assistant

    ports:
      - "8501:8501"

    env_file:
      - .env

    volumes:
      - ./chroma_db:/app/chroma_db
      - ./data:/app/data

    restart: unless-stopped